export const productColumn = [
  {
    title: "№",
    dataIndex: "colIndex",
    key: "colIndex",
    width: 40,
    align: "center",
  },
  {
    title: "Nomi",
    dataIndex: "name",
    key: "name",
    width: 150,
    align: "center",
  },
  {
    title: "Modeli",
    dataIndex: "model",
    key: "model",
    width: 100,
    align: "center",
  },
  {
    title: "Turi",
    dataIndex: "type",
    key: "type",
    width: 100,
    align: "center",
  },
  {
    title: "Egasi",
    dataIndex: "createdBy",
    key: "createdBy",
    width: 120,
    align: "center",
  },
  {
    title: "Narxi",
    dataIndex: "price",
    key: "price",
    width: 100,
    align: "center",
  },
  {
    title: "Chegirmasi",
    dataIndex: "discount",
    key: "discount",
    width: 100,
    align: "center",
  },
  {
    title: "Chegirmadagi",
    dataIndex: "discountPrice",
    key: "discountPrice",
    width: 100,
    align: "center",
  },
  {
    title: "Amallar",
    dataIndex: "actions",
    key: "actions",
    width: 60,
    align: "center",
  },
];
