export const userColumns = [
  {
    title: "№",
    dataIndex: "colIndex",
    key: "colIndex",
    width: 50,
    align: "center",
  },
  {
    title: "Profili",
    dataIndex: "avatarUrl",
    key: "avatarUrl",
    width: 70,
    align: "center",
  },
  {
    title: "Ismi",
    dataIndex: "name",
    key: "name",
    width: 150,
    align: "center",
  },
  {
    title: "Familyasi",
    dataIndex: "surname",
    key: "surname",
    width: 150,
    align: "center",
  },
  {
    title: "Roli",
    dataIndex: "role",
    key: "role",
    width: 140,
    align: "center",
  },
  {
    title: "Foydalanuvchi nomi",
    dataIndex: "userName",
    key: "userName",
    width: 130,
    align: "center",
  },
  {
    title: "Raqami",
    dataIndex: "phone",
    key: "phone",
    width: 130,
    align: "center",
  },
  {
    title: "Amallar",
    dataIndex: "actions",
    key: "actions",
    width: 80,
    align: "center",
  },
];
